# Meta Data for SEO

## Homepage
title = "OpenPPG Config"
titleSeparator = "-"
titleAddition = "Config Tool for OpenPPG"
description = "Easily adjust settings on your OpenPPG X4 or OpenPPG SP140"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "openppg"
twitterCreator = "openppg"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/openppg"
schemaLinkedIn = "https://www.linkedin.com/in/openppg/"
schemaGitHub = "https://github.com/openppg"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false
